# Generated by Django 5.1.5 on 2025-02-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seats",
            name="number",
        ),
        migrations.RemoveField(
            model_name="seats",
            name="seat_type",
        ),
        migrations.AddField(
            model_name="seats",
            name="number_normal_seats",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="seats",
            name="number_vip_seats",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
