# Generated by Django 5.1.5 on 2025-02-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_seats_number_remove_seats_seat_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="number_normal_seats",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="seats",
            name="number_vip_seats",
            field=models.IntegerField(editable=False),
        ),
    ]
