# Generated by Django 5.1.5 on 2025-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_ticket_seat_ticket_movie_shedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seats",
            name="fix_normal_seats",
            field=models.IntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seats",
            name="fix_vip_seats",
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_number",
            field=models.IntegerField(default=4, editable=False),
            preserve_default=False,
        ),
    ]
